import Header from "@/components/header/Header";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {

  const router = useRouter()
  return (
    <>
      <Head>
        <title>Exchange Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />
        <button onClick={() => router.push('/dashboard')}>Go to dashboard</button>
      </div>

    </>
  );
}
